#!/usr/bin/env bash
# install.sh — FoxRouters one-liner installer (no docker-compose needed)
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/rilspratama/Foxrouters/master/install.sh | bash
#
# Or clone + run:
#   ./install.sh
#
# What it does:
#   1. Checks/installs Docker
#   2. Creates dedicated network + volumes
#   3. Pulls and starts Redis, ClickHouse, and FoxRouters containers
#   4. Generates random Redis password + bootstraps gateway admin key
#   5. Prints gateway key + dashboard URL
#
# Manage after install:
#   docker logs foxrouters -f              # tail logs
#   docker restart foxrouters              # restart gateway
#   docker stop foxrouters foxrouters-redis foxrouters-clickhouse  # stop all
#   docker start foxrouters-redis foxrouters-clickhouse foxrouters  # start all
#   docker rm -f foxrouters foxrouters-redis foxrouters-clickhouse  # remove (keeps volumes)
#   docker volume rm foxrouters-redis-data foxrouters-clickhouse-data  # wipe data
#
set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────
IMAGE_GATEWAY="ghcr.io/rilspratama/foxrouters:latest"
IMAGE_REDIS="redis:7-alpine"
IMAGE_CLICKHOUSE="clickhouse/clickhouse-server:latest"
GATEWAY_PORT="${FOXROUTERS_PORT:-20130}"
REDIS_PORT="${REDIS_PORT:-6379}"
CH_HTTP_PORT="${CH_HTTP_PORT:-8123}"
CH_NATIVE_PORT="${CH_NATIVE_PORT:-9000}"
NETWORK="foxrouters-net"
VOL_REDIS="foxrouters-redis-data"
VOL_CH="foxrouters-clickhouse-data"
CONFIG_DIR="/etc/foxrouters"
ENV_FILE="${CONFIG_DIR}/.env"
KEY_FILE="${CONFIG_DIR}/gateway-key.txt"

# ── Colors ───────────────────────────────────────────────────────────────────
red()    { printf '\033[31m%s\033[0m\n' "$*"; }
green()  { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
bold()   { printf '\033[1m%s\033[0m\n' "$*"; }
info()   { printf '\033[36m[i]\033[0m %s\n' "$*"; }
ok()     { printf '\033[32m[✓]\033[0m %s\n' "$*"; }
err()    { printf '\033[31m[✗]\033[0m %s\n' "$*"; }

# ── Step 1: Docker check/install ────────────────────────────────────────────
info "Checking Docker..."
if ! command -v docker &>/dev/null; then
    yellow "Docker not found. Installing..."
    # Try official install script
    if command -v curl &>/dev/null; then
        curl -fsSL https://get.docker.com | sh
    elif command -v wget &>/dev/null; then
        wget -qO- https://get.docker.com | sh
    else
        err "Cannot install Docker: neither curl nor wget found."
        err "Install Docker manually: https://docs.docker.com/engine/install/"
        exit 1
    fi
    # Start Docker service
    systemctl start docker 2>/dev/null || service docker start 2>/dev/null || true
    systemctl enable docker 2>/dev/null || true
    ok "Docker installed"
else
    ok "Docker found: $(docker --version)"
fi

# Verify Docker daemon is running
if ! docker info &>/dev/null; then
    err "Docker daemon not running. Start it with: systemctl start docker"
    exit 1
fi

# ── Step 2: Generate secrets ────────────────────────────────────────────────
info "Generating secrets..."
REDIS_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p)
CH_PASSWORD=""  # ClickHouse default user has no password by default

# Create config directory
mkdir -p "${CONFIG_DIR}"
chmod 700 "${CONFIG_DIR}"

# Write env file (for reference / re-deploy)
cat > "${ENV_FILE}" << EOF
# FoxRouters Docker deployment — generated by install.sh
# Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
REDIS_ADDR=redis:6379
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_DB=0
CLICKHOUSE_ADDR=clickhouse:9000
CLICKHOUSE_DB=gateway
CLICKHOUSE_USER=default
CLICKHOUSE_PASSWORD=${CH_PASSWORD}
PORT=${GATEWAY_PORT}
COOKIE_SECURE=0
EOF
chmod 600 "${ENV_FILE}"
ok "Secrets generated → ${ENV_FILE}"

# ── Step 3: Create network + volumes ─────────────────────────────────────────
info "Creating Docker network + volumes..."
docker network create "${NETWORK}" 2>/dev/null || ok "Network ${NETWORK} already exists"
docker volume create "${VOL_REDIS}" 2>/dev/null || ok "Volume ${VOL_REDIS} already exists"
docker volume create "${VOL_CH}" 2>/dev/null || ok "Volume ${VOL_CH} already exists"

# ── Step 4: Pull images ─────────────────────────────────────────────────────
info "Pulling images (this may take a few minutes on first run)..."
docker pull "${IMAGE_REDIS}"        2>&1 | tail -1
docker pull "${IMAGE_CLICKHOUSE}"   2>&1 | tail -1
docker pull "${IMAGE_GATEWAY}"      2>&1 | tail -1
ok "Images pulled"

# ── Step 5: Start Redis ─────────────────────────────────────────────────────
info "Starting Redis..."
docker rm -f foxrouters-redis 2>/dev/null || true
docker run -d \
    --name foxrouters-redis \
    --network "${NETWORK}" \
    --network-alias redis \
    -p "127.0.0.1:${REDIS_PORT}:6379" \
    -v "${VOL_REDIS}:/data" \
    --restart unless-stopped \
    "${IMAGE_REDIS}" \
    redis-server --requirepass "${REDIS_PASSWORD}" --appendonly no
ok "Redis started (port ${REDIS_PORT})"

# ── Step 6: Start ClickHouse ────────────────────────────────────────────────
info "Starting ClickHouse..."
docker rm -f foxrouters-clickhouse 2>/dev/null || true
docker run -d \
    --name foxrouters-clickhouse \
    --network "${NETWORK}" \
    --network-alias clickhouse \
    -p "127.0.0.1:${CH_HTTP_PORT}:8123" \
    -p "127.0.0.1:${CH_NATIVE_PORT}:9000" \
    -v "${VOL_CH}:/var/lib/clickhouse" \
    --ulimit nofile=262144:262144 \
    --restart unless-stopped \
    -e CLICKHOUSE_USER=default \
    -e CLICKHOUSE_PASSWORD="${CH_PASSWORD}" \
    -e CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1 \
    "${IMAGE_CLICKHOUSE}"
ok "ClickHouse started (HTTP ${CH_HTTP_PORT}, Native ${CH_NATIVE_PORT})"

# ── Step 7: Wait for Redis + CH healthy ─────────────────────────────────────
info "Waiting for Redis + ClickHouse to be healthy..."
for i in $(seq 1 30); do
    REDIS_OK=$(docker exec foxrouters-redis redis-cli -a "${REDIS_PASSWORD}" ping 2>/dev/null || echo "FAIL")
    CH_OK=$(curl -sf "http://127.0.0.1:${CH_HTTP_PORT}/ping" 2>/dev/null || echo "FAIL")
    if [[ "${REDIS_OK}" == "PONG" && "${CH_OK}" == "Ok." ]]; then
        ok "Redis + ClickHouse healthy"
        break
    fi
    printf "."
    sleep 2
    if [[ $i -eq 30 ]]; then
        err "Timeout waiting for Redis + ClickHouse"
        docker logs foxrouters-redis --tail 5
        docker logs foxrouters-clickhouse --tail 5
        exit 1
    fi
done

# ── Step 8: Start FoxRouters gateway ────────────────────────────────────────
info "Starting FoxRouters gateway..."
docker rm -f foxrouters 2>/dev/null || true
docker run -d \
    --name foxrouters \
    --network "${NETWORK}" \
    -p "127.0.0.1:${GATEWAY_PORT}:20130" \
    --restart unless-stopped \
    --env-file "${ENV_FILE}" \
    -e REDIS_ADDR=redis:6379 \
    -e CLICKHOUSE_ADDR=clickhouse:9000 \
    -e CLICKHOUSE_DB=gateway \
    -e CLICKHOUSE_USER=default \
    -e CLICKHOUSE_PASSWORD="${CH_PASSWORD}" \
    -e PORT=20130 \
    "${IMAGE_GATEWAY}"
ok "FoxRouters started (port ${GATEWAY_PORT})"

# ── Step 9: Capture gateway key from Redis ──────────────────────────────────
# Redis is the single source of truth. Gateway writes the bootstrap key to
# Redis on first boot, or loads existing keys on re-deploy. Either way,
# the full (unmasked) key is in HASH gw:key:* field "key".
info "Waiting for gateway to write key to Redis (up to 30s)..."
BOOTSTRAP_KEY=""
for i in $(seq 1 30); do
    EXISTING_KEY=$(docker exec foxrouters-redis redis-cli -a "${REDIS_PASSWORD}" --scan --pattern 'gw:key:*' 2>/dev/null | head -1 || true)
    if [[ -n "${EXISTING_KEY}" ]]; then
        BOOTSTRAP_KEY=$(docker exec foxrouters-redis redis-cli -a "${REDIS_PASSWORD}" hget "${EXISTING_KEY}" key 2>/dev/null | tr -d '\r\n' || true)
        if [[ -n "${BOOTSTRAP_KEY}" ]]; then
            break
        fi
    fi
    printf "."
    sleep 1
done

if [[ -z "${BOOTSTRAP_KEY}" ]]; then
    err "Gateway did not write a key to Redis within 30s."
    err "Check logs: docker logs foxrouters"
    exit 1
fi

echo "${BOOTSTRAP_KEY}" > "${KEY_FILE}"
chmod 600 "${KEY_FILE}"
ok "Gateway key captured → ${KEY_FILE}"

# ── Step 10: Health check ───────────────────────────────────────────────────
info "Health check..."
sleep 3
HEALTH=$(curl -sf "http://127.0.0.1:${GATEWAY_PORT}/health" 2>/dev/null || echo "FAIL")
if echo "${HEALTH}" | grep -q "healthy"; then
    ok "Gateway healthy: ${HEALTH}"
else
    err "Gateway not healthy yet. Check: docker logs foxrouters"
    err "Response: ${HEALTH}"
fi

# ── Summary ─────────────────────────────────────────────────────────────────
echo ""
bold "═══════════════════════════════════════════════════════════════"
bold "  FoxRouters installed successfully!"
bold "═══════════════════════════════════════════════════════════════"
echo ""
if [[ -n "${BOOTSTRAP_KEY}" ]]; then
    green "  Gateway Key:  ${BOOTSTRAP_KEY}"
    echo ""
    yellow "  ⚠  Save this key — it won't be shown again."
    yellow "     Stored at: ${KEY_FILE}"
    echo ""
fi
echo "  Dashboard:    http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost'):${GATEWAY_PORT}/dashboard"
echo "  API Base:     http://localhost:${GATEWAY_PORT}/v1/chat/completions"
echo "  Health:       http://localhost:${GATEWAY_PORT}/health"
echo ""
echo "  Config:       ${ENV_FILE}"
echo ""
echo "  Manage:"
echo "    docker logs foxrouters -f           # tail logs"
echo "    docker restart foxrouters           # restart gateway"
echo "    docker stop foxrouters-redis foxrouters-clickhouse foxrouters  # stop all"
echo "    docker start foxrouters-redis foxrouters-clickhouse foxrouters  # start all"
echo "    docker rm -f foxrouters foxrouters-redis foxrouters-clickhouse  # remove (keeps data)"
echo ""
bold "═══════════════════════════════════════════════════════════════"
