#!/usr/bin/env bash
# install.sh — FoxRouters one-liner installer (no docker-compose needed)
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/rilspratama/Foxrouters/master/install.sh | bash
#
# Or clone + run:
#   ./install.sh
#
# What it does:
#   1. Checks/installs Docker
#   2. Prompts for log backend (SQLite default; ClickHouse optional)
#   3. Creates dedicated network + volumes
#   4. Pulls and starts Redis (+ ClickHouse if selected) + FoxRouters containers
#   5. Generates random Redis password + bootstraps gateway admin key
#   6. Prints gateway key + dashboard URL
#
# Non-interactive mode:
#   Set LOG_BACKEND=sqlite     (default) or LOG_BACKEND=clickhouse before piping to bash.
#     curl -fsSL … | LOG_BACKEND=clickhouse bash
#
# Manage after install:
#   docker logs foxrouters -f
#   docker restart foxrouters
#   docker rm -f foxrouters foxrouters-redis [foxrouters-clickhouse]   # remove (keeps volumes)
#
set -euo pipefail

# ── Config ──────────────────────────────────────────────────────────────────
IMAGE_GATEWAY="${IMAGE_GATEWAY:-ghcr.io/rilspratama/foxrouters:latest}"
IMAGE_REDIS="redis:7-alpine"
IMAGE_CLICKHOUSE="clickhouse/clickhouse-server:latest"
GATEWAY_PORT="${FOXROUTERS_PORT:-20130}"
REDIS_PORT="${REDIS_PORT:-6379}"
CH_HTTP_PORT="${CH_HTTP_PORT:-8123}"
CH_NATIVE_PORT="${CH_NATIVE_PORT:-9000}"
NETWORK="foxrouters-net"
VOL_REDIS="foxrouters-redis-data"
VOL_CH="foxrouters-clickhouse-data"
VOL_SQLITE="foxrouters-sqlite-data"
CONFIG_DIR="/etc/foxrouters"
ENV_FILE="${CONFIG_DIR}/.env"
KEY_FILE="${CONFIG_DIR}/gateway-key.txt"
TUNNEL_CONFIG_DIR="${CONFIG_DIR}/cloudflared"
TUNNEL_CONTAINER="foxrouters-tunnel"
IMAGE_TUNNEL="cloudflare/cloudflared:latest"

# ── Colors ───────────────────────────────────────────────────────────────────
red()    { printf '\033[31m%s\033[0m\n' "$*"; }
green()  { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
bold()   { printf '\033[1m%s\033[0m\n' "$*"; }
info()   { printf '\033[36m[i]\033[0m %s\n' "$*"; }
ok()     { printf '\033[32m[✓]\033[0m %s\n' "$*"; }
err()    { printf '\033[31m[✗]\033[0m %s\n' "$*"; }

# ── Step 1: Docker check/install ────────────────────────────────────────────
info "Checking Docker..."
if ! command -v docker &>/dev/null; then
    yellow "Docker not found. Installing..."
    if command -v curl &>/dev/null; then
        curl -fsSL https://get.docker.com | sh
    elif command -v wget &>/dev/null; then
        wget -qO- https://get.docker.com | sh
    else
        err "Cannot install Docker: neither curl nor wget found."
        err "Install Docker manually: https://docs.docker.com/engine/install/"
        exit 1
    fi
    systemctl start docker 2>/dev/null || service docker start 2>/dev/null || true
    systemctl enable docker 2>/dev/null || true
    ok "Docker installed"
else
    ok "Docker found: $(docker --version)"
fi

if ! docker info &>/dev/null; then
    err "Docker daemon not running. Start it with: systemctl start docker"
    exit 1
fi

# ── Step 2: Prompt for log backend ──────────────────────────────────────────
# Priority:
#   1. LOG_BACKEND env var (non-interactive install)
#   2. Interactive prompt (only if stdin is a TTY)
#   3. Default: sqlite
LOG_BACKEND="${LOG_BACKEND:-}"
if [[ -z "${LOG_BACKEND}" ]]; then
    if [[ -t 0 ]]; then
        echo ""
        bold "Log backend"
        echo "  [1] SQLite     (default, lightweight, ~0 ops cost — recommended)"
        echo "  [2] ClickHouse (analytics; adds ~700MB image + a service to maintain)"
        echo ""
        read -r -p "Choice [1]: " CHOICE || CHOICE=""
        case "${CHOICE}" in
            2|ch|clickhouse) LOG_BACKEND="clickhouse" ;;
            *)               LOG_BACKEND="sqlite"     ;;
        esac
    else
        # Piped install with no LOG_BACKEND set → default to sqlite.
        LOG_BACKEND="sqlite"
    fi
fi
case "${LOG_BACKEND}" in
    sqlite|clickhouse) ok "Log backend: ${LOG_BACKEND}" ;;
    *)
        err "Unknown LOG_BACKEND=${LOG_BACKEND} — must be sqlite or clickhouse"
        exit 1
        ;;
esac

# ── Step 3: Generate secrets ────────────────────────────────────────────────
info "Generating secrets..."
REDIS_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | xxd -p)
CH_PASSWORD=""  # ClickHouse default user has no password by default

mkdir -p "${CONFIG_DIR}"
chmod 700 "${CONFIG_DIR}"

# Write env file (for reference / re-deploy)
cat > "${ENV_FILE}" << EOF
# FoxRouters Docker deployment — generated by install.sh
# Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
REDIS_ADDR=redis:6379
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_DB=0
LOG_BACKEND=${LOG_BACKEND}
LOG_SQLITE_PATH=/var/lib/foxrouters/logs.db
CLICKHOUSE_ADDR=clickhouse:9000
CLICKHOUSE_DB=gateway
CLICKHOUSE_USER=default
CLICKHOUSE_PASSWORD=${CH_PASSWORD}
PORT=${GATEWAY_PORT}
COOKIE_SECURE=0
EOF
chmod 600 "${ENV_FILE}"
ok "Secrets generated → ${ENV_FILE}"

# ── Step 4: Create network + volumes ─────────────────────────────────────────
info "Creating Docker network + volumes..."
docker network create "${NETWORK}"    2>/dev/null || ok "Network ${NETWORK} already exists"
docker volume  create "${VOL_REDIS}"  2>/dev/null || ok "Volume ${VOL_REDIS} already exists"
docker volume  create "${VOL_SQLITE}" 2>/dev/null || ok "Volume ${VOL_SQLITE} already exists"

# Fix volume ownership: gateway runs as UID 1000 (non-root).
# Without this, SQLite can't write to /var/lib/foxrouters/logs.db.
docker run --rm -v "${VOL_SQLITE}:/data" alpine chown -R 1000:1000 /data 2>/dev/null || true
if [[ "${LOG_BACKEND}" == "clickhouse" ]]; then
    docker volume create "${VOL_CH}" 2>/dev/null || ok "Volume ${VOL_CH} already exists"
fi

# ── Step 5: Pull images ─────────────────────────────────────────────────────
info "Pulling images (this may take a few minutes on first run)..."
docker pull "${IMAGE_REDIS}"      2>&1 | tail -1
if [[ "${LOG_BACKEND}" == "clickhouse" ]]; then
    docker pull "${IMAGE_CLICKHOUSE}"  2>&1 | tail -1
fi
# Only pull gateway if not already present locally (avoid overwriting local builds)
if ! docker image inspect "${IMAGE_GATEWAY}" &>/dev/null; then
    docker pull "${IMAGE_GATEWAY}"    2>&1 | tail -1
else
    ok "Gateway image found locally: ${IMAGE_GATEWAY}"
fi
ok "Images pulled"

# ── Step 6: Start Redis ─────────────────────────────────────────────────────
info "Starting Redis..."
docker rm -f foxrouters-redis 2>/dev/null || true
docker run -d \
    --name foxrouters-redis \
    --network "${NETWORK}" \
    --network-alias redis \
    -p "127.0.0.1:${REDIS_PORT}:6379" \
    -v "${VOL_REDIS}:/data" \
    --restart unless-stopped \
    "${IMAGE_REDIS}" \
    redis-server --requirepass "${REDIS_PASSWORD}" --appendonly no
ok "Redis started (port ${REDIS_PORT})"

# ── Step 7: Start ClickHouse (only if selected) ─────────────────────────────
if [[ "${LOG_BACKEND}" == "clickhouse" ]]; then
    info "Starting ClickHouse..."
    docker rm -f foxrouters-clickhouse 2>/dev/null || true
    docker run -d \
        --name foxrouters-clickhouse \
        --network "${NETWORK}" \
        --network-alias clickhouse \
        -p "127.0.0.1:${CH_HTTP_PORT}:8123" \
        -p "127.0.0.1:${CH_NATIVE_PORT}:9000" \
        -v "${VOL_CH}:/var/lib/clickhouse" \
        --ulimit nofile=262144:262144 \
        --restart unless-stopped \
        -e CLICKHOUSE_USER=default \
        -e CLICKHOUSE_PASSWORD="${CH_PASSWORD}" \
        -e CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1 \
        "${IMAGE_CLICKHOUSE}"
    ok "ClickHouse started (HTTP ${CH_HTTP_PORT}, Native ${CH_NATIVE_PORT})"
else
    info "SQLite mode — skipping ClickHouse container"
    # Best-effort cleanup of a stale CH container from a prior CH install.
    docker rm -f foxrouters-clickhouse 2>/dev/null || true
fi

# ── Step 8: Wait for dependencies healthy ───────────────────────────────────
info "Waiting for Redis${LOG_BACKEND:+ + ${LOG_BACKEND}} to be healthy..."
for i in $(seq 1 30); do
    REDIS_OK=$(docker exec foxrouters-redis redis-cli -a "${REDIS_PASSWORD}" ping 2>/dev/null || echo "FAIL")
    if [[ "${LOG_BACKEND}" == "clickhouse" ]]; then
        CH_OK=$(curl -sf "http://127.0.0.1:${CH_HTTP_PORT}/ping" 2>/dev/null || echo "FAIL")
    else
        CH_OK="Ok."
    fi
    if [[ "${REDIS_OK}" == "PONG" && "${CH_OK}" == "Ok." ]]; then
        ok "Dependencies healthy"
        break
    fi
    printf "."
    sleep 2
    if [[ $i -eq 30 ]]; then
        err "Timeout waiting for dependencies"
        docker logs foxrouters-redis --tail 5
        [[ "${LOG_BACKEND}" == "clickhouse" ]] && docker logs foxrouters-clickhouse --tail 5
        exit 1
    fi
done

# ── Step 9: Start FoxRouters gateway ────────────────────────────────────────
info "Starting FoxRouters gateway..."
docker rm -f foxrouters 2>/dev/null || true
docker run -d \
    --name foxrouters \
    --network "${NETWORK}" \
    -p "127.0.0.1:${GATEWAY_PORT}:20130" \
    -v "${VOL_SQLITE}:/var/lib/foxrouters" \
    --restart unless-stopped \
    --env-file "${ENV_FILE}" \
    -e REDIS_ADDR=redis:6379 \
    -e LOG_BACKEND="${LOG_BACKEND}" \
    -e LOG_SQLITE_PATH=/var/lib/foxrouters/logs.db \
    -e CLICKHOUSE_ADDR=clickhouse:9000 \
    -e CLICKHOUSE_DB=gateway \
    -e CLICKHOUSE_USER=default \
    -e CLICKHOUSE_PASSWORD="${CH_PASSWORD}" \
    -e PORT=20130 \
    "${IMAGE_GATEWAY}"
ok "FoxRouters started (port ${GATEWAY_PORT}, log backend: ${LOG_BACKEND})"

# ── Step 10: Capture gateway key from Redis ─────────────────────────────────
info "Waiting for gateway to write key to Redis (up to 30s)..."
BOOTSTRAP_KEY=""
for i in $(seq 1 30); do
    EXISTING_KEY=$(docker exec foxrouters-redis redis-cli -a "${REDIS_PASSWORD}" --scan --pattern 'gw:key:*' 2>/dev/null | head -1 || true)
    if [[ -n "${EXISTING_KEY}" ]]; then
        BOOTSTRAP_KEY=$(docker exec foxrouters-redis redis-cli -a "${REDIS_PASSWORD}" hget "${EXISTING_KEY}" key 2>/dev/null | tr -d '\r\n' || true)
        if [[ -n "${BOOTSTRAP_KEY}" ]]; then
            break
        fi
    fi
    printf "."
    sleep 1
done

if [[ -z "${BOOTSTRAP_KEY}" ]]; then
    err "Gateway did not write a key to Redis within 30s."
    err "Check logs: docker logs foxrouters"
    exit 1
fi

echo "${BOOTSTRAP_KEY}" > "${KEY_FILE}"
chmod 600 "${KEY_FILE}"
ok "Gateway key captured → ${KEY_FILE}"

# ── Step 11: Health check ───────────────────────────────────────────────────
info "Health check..."
sleep 3
HEALTH=$(curl -sf "http://127.0.0.1:${GATEWAY_PORT}/health" 2>/dev/null || echo "FAIL")
if echo "${HEALTH}" | grep -q "healthy"; then
    ok "Gateway healthy: ${HEALTH}"
else
    err "Gateway not healthy yet. Check: docker logs foxrouters"
    err "Response: ${HEALTH}"
fi

# ── Step 12: Cloudflare Tunnel (optional) ───────────────────────────────────
# Priority:
#   1. TUNNEL_MODE env var (non-interactive install: quick|named|none)
#   2. Interactive prompt (only if stdin is a TTY)
#   3. Default: none (piped installs stay tunnel-free)
TUNNEL_MODE="${TUNNEL_MODE:-}"
if [[ -z "${TUNNEL_MODE}" ]]; then
    if [[ -t 0 ]]; then
        echo ""
        bold "Cloudflare Tunnel"
        echo "  Expose the gateway publicly via Cloudflare (no firewall changes)."
        echo "  [1] Quick — random *.trycloudflare.com URL (no domain, no login)"
        echo "  [2] Named — custom domain (requires prior cloudflared login + create)"
        echo "  [3] No tunnel"
        echo ""
        read -r -p "Choice [3]: " TCHOICE || TCHOICE=""
        case "${TCHOICE}" in
            1|q|quick) TUNNEL_MODE="quick" ;;
            2|n|named) TUNNEL_MODE="named" ;;
            *)         TUNNEL_MODE="none"  ;;
        esac
    else
        TUNNEL_MODE="none"
    fi
fi
case "${TUNNEL_MODE}" in
    none|quick|named) ;;
    *)
        err "Unknown TUNNEL_MODE=${TUNNEL_MODE} — must be none, quick, or named"
        exit 1
        ;;
esac

TUNNEL_URL=""
if [[ "${TUNNEL_MODE}" == "quick" ]]; then
    info "Starting Cloudflare quick tunnel..."
    docker pull "${IMAGE_TUNNEL}" 2>&1 | tail -1 || true
    docker rm -f "${TUNNEL_CONTAINER}" 2>/dev/null || true
    docker run -d \
        --name "${TUNNEL_CONTAINER}" \
        --network "${NETWORK}" \
        --restart unless-stopped \
        "${IMAGE_TUNNEL}" \
        tunnel --no-autoupdate --url "http://foxrouters:20130" >/dev/null
    mkdir -p "${TUNNEL_CONFIG_DIR}"
    echo "quick" > "${TUNNEL_CONFIG_DIR}/mode"
    info "Waiting for tunnel URL (up to 30s)..."
    for _ in $(seq 1 30); do
        TUNNEL_URL=$(docker logs "${TUNNEL_CONTAINER}" 2>&1 \
            | grep -oE 'https://[a-zA-Z0-9.-]+\.trycloudflare\.com' \
            | head -1 || true)
        [[ -n "${TUNNEL_URL}" ]] && break
        sleep 1
    done
    if [[ -n "${TUNNEL_URL}" ]]; then
        ok "Tunnel URL: ${TUNNEL_URL}"
    else
        err "Could not capture tunnel URL. Check: docker logs ${TUNNEL_CONTAINER}"
    fi
elif [[ "${TUNNEL_MODE}" == "named" ]]; then
    info "Named tunnel selected — auto-start skipped (needs prior setup)."
    echo ""
    yellow "  Named tunnels require manual one-time setup:"
    echo "    1. cloudflared tunnel login"
    echo "    2. cloudflared tunnel create foxrouters"
    echo "    3. sudo mkdir -p ${TUNNEL_CONFIG_DIR}"
    echo "       sudo cp ~/.cloudflared/cert.pem        ${TUNNEL_CONFIG_DIR}/"
    echo "       sudo cp ~/.cloudflared/<tunnel>.json   ${TUNNEL_CONFIG_DIR}/"
    echo "    4. Write ${TUNNEL_CONFIG_DIR}/config.yml with ingress rules"
    echo "    5. cloudflared tunnel route dns foxrouters gateway.example.com"
    echo "    6. ./tunnel.sh enable --named"
    echo ""
fi

# ── Summary ─────────────────────────────────────────────────────────────────
echo ""
bold "═══════════════════════════════════════════════════════════════"
bold "  FoxRouters installed successfully!"
bold "═══════════════════════════════════════════════════════════════"
echo ""
if [[ -n "${BOOTSTRAP_KEY}" ]]; then
    green "  Gateway Key:  ${BOOTSTRAP_KEY}"
    echo ""
    yellow "  ⚠  Save this key — it won't be shown again."
    yellow "     Stored at: ${KEY_FILE}"
    echo ""
fi
echo "  Dashboard:    http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost'):${GATEWAY_PORT}/dashboard"
echo "  API Base:     http://localhost:${GATEWAY_PORT}/v1/chat/completions"
echo "  Health:       http://localhost:${GATEWAY_PORT}/health"
echo "  Log backend:  ${LOG_BACKEND}"
if [[ "${TUNNEL_MODE}" == "quick" && -n "${TUNNEL_URL}" ]]; then
    echo "  Tunnel:       ${TUNNEL_URL}  (quick — URL changes on restart)"
elif [[ "${TUNNEL_MODE}" == "named" ]]; then
    echo "  Tunnel:       named (finish setup, then ./tunnel.sh enable --named)"
else
    echo "  Tunnel:       disabled  (./tunnel.sh enable to add one later)"
fi
echo ""
echo "  Config:       ${ENV_FILE}"
echo ""
echo "  Manage:"
echo "    docker logs foxrouters -f           # tail logs"
echo "    docker restart foxrouters           # restart gateway"
if [[ "${LOG_BACKEND}" == "clickhouse" ]]; then
    echo "    docker stop foxrouters-redis foxrouters-clickhouse foxrouters"
    echo "    docker start foxrouters-redis foxrouters-clickhouse foxrouters"
    echo "    docker rm -f foxrouters foxrouters-redis foxrouters-clickhouse"
else
    echo "    docker stop foxrouters-redis foxrouters"
    echo "    docker start foxrouters-redis foxrouters"
    echo "    docker rm -f foxrouters foxrouters-redis"
fi
echo ""
bold "═══════════════════════════════════════════════════════════════"
